#!/bin/bash

FILE=~/DataSets/Pokemon/NationalPokedex.csv

usage()
{
	echo "$0" <command> [<args>]
	echo Commands
	echo 	list		list all types
	echo 	countType	count total number of type as arg
}

list() 
{
	cat $FILE | cut -d , -f 4 | sort | uniq | grep -v Type1
}

countType()
{
	NUM1=$FILE | cut -d , -f 4 | grep "$1" | uniq -c
	NUM2=$FILE | cut -d , -f 5 | grep "$1" | uniq -c
	declare -i NUM1 NUM2
	$NUM1 += $NUM2
	echo $NUM1
}

"$@"
