#!/bin/bash

FILE=~/DataSets/Pokemon/NationalPokedex.csv

usage()
{
	echo "$0" <command> [<args>]
	echo Commands
	echo 	list		list all types
	echo 	countType	count total number of type as arg
}

list() 
{
	cat $FILE | cut -d , -f 4 | sort | uniq | grep -v Type1
}

countType()
{
	cat $FILE | cut -d , -f 4 | grep "$1" | uniq -c
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

"$@"


